spring:
  application:
    name: Springdeed

  docker:
    compose:
      file: ../services/compose.yaml

  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/springdeed/.well-known/openid-configuration
